# Generated by Django 2.1.7 on 2025-02-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20250202_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
